---
- hosts: mail
  gather_facts: no

  tasks:
    - name: update apt cache
      apt:
        update_cache: yes

    - name: Installs necessary packages
      apt:
        pkg: '{{item}}'
        state: present
      with_items:
        - postfix
        - dovecot-common
        - dovecot-imapd

    - name: Copies postfix conf files
      copy: src=files/postfix/{{item}}
            dest=/etc/postfix/{{item}}
            mode=0400
      with_items:
        - main.cf
        - master.cf

    - name: Copies dovecot conf files
      copy: src=files/dovecot/{{item}}
            dest=/etc/dovecot/conf.d/{{item}}
            mode=0400
      with_items:
        - 10-ssl.conf
        - 10-auth.conf
        - 10-master.conf
